export const COMPRESS = 'COMPRESS';

export const SHOW_LOGIN = 'SHOW_LOGIN';

export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const ADD_COMPARE = 'ADD_COMPARE';
export const REMOVE_COMPARE = 'REMOVE_COMPARE';

export const LOG_USER_REQUEST = 'LOG_USER_REQUEST';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_FAILURE = 'LOG_USER_FAILURE';
