export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';
export const MAKE_SUBMIT = 'MAKE_SUBMIT';

export const GOAL_REQUEST = 'GOAL_REQUEST';
export const GOAL_FAILURE = 'GOAL_FAILURE';
export const ADD_GOAL = 'ADD_GOAL';
export const REMOVE_GOAL = 'REMOVE_GOAL';
export const GET_GOALS = 'GET_GOALS';

export const ADD_COMPARE = 'ADD_COMPARE';
export const REMOVE_COMPARE = 'REMOVE_COMPARE';

export const SETUP_USER = 'SETUP_USER';
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
export const LOG_USER_REQUEST = 'LOG_USER_REQUEST';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_FAILURE = 'LOG_USER_FAILURE';
export const SIGN_USER_REQUEST = 'SIGN_USER_REQUEST';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_FAILURE = 'SIGN_USER_FAILURE';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';


export const ESSAY_REQUEST = 'ESSAYS_REQUEST';
export const ESSAY_FAILURE = 'ESSAYS_FAILURE';
export const ADD_ESSAY = 'ADD_ESSAY';
export const REMOVE_ESSAY = 'REMAOVE_ESSAY';
export const GET_ESSAYS = 'GET_ESSAYS';


export const CLEAR_STATE = 'CLEAR_STATE';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const INFINITE_REQUEST = 'INFINITE_REQUEST';
export const INFINITE_SUCCESS = 'INFINITE_SUCCESS';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const POPULAR_SUCCESS = 'POPULAR_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';

export const OBJECTIVES_REQUEST = 'OBJECTIVES_REQUEST';
export const OBJECTIVES_FAILURE = 'OBJECTIVES_FAULIRE';
export const GET_OBJECTIVES = 'GET_OBJECTIVES';
export const UPDATE_OBJECTIVES = 'UPDATE_OBJECTIVES';
