const initialState = {
  1512: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_administracion_publica.html',
  1513: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_arquitectura.html',
  1514: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_arquitectura_paisaje.html',
  1515: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ciencia_politica.html',
  1516: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_contador_auditor.html',
  1517: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_derecho.html',
  1518: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_derecho.html',
  1519: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_educacion_parvularia.html',
  1520: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_enfermeria.html',
  1521: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_geologia.html',
  1522: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_civil_computacion_informatica.html',
  1523: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_civil_minas.html',
  1524: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_civil_obras_civiles.html',
  1525: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_civil_industrial.html',
  1526: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_comercial.html',
  1527: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_comercial.html',
  1528: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_ejecucion_administracion_negocios.html',
  1529: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_agronegocios.html',
  1530: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingenieria_construccion.html',
  1531: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_ingeniria_control_gestion.html',
  1532: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_nutricion_y_dietetica.html',
  1533: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_educacion_diferencial.html',
  1534: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_educacion_diferencial.html',
  1535: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_pedagogia_educacion_fisica.html',
  1536: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_pedagogia_educacion_fisica.html',
  1537: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_pedagodia_educacion_general_basica.html',
  1538: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_pedagogia_lengua_cultura_inglesas.html',
  1539: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_pedagogia_matematica_estadistica.html',
  1540: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_periodismo.html',
  1541: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_psicologia.html',
  1542: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_psicologia.html',
  1543: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_publicidad.html',
  1544: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_sociologia.html',
  1545: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_sociologia.html',
  1546: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_tecnologia_medica.html',
  1547: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_terapia_ocupacional.html',
  1548: 'http://www.ucentral.cl/prontus_ucentral2012/site/edic/base/port/f_trabajo_social.html',
  1610: 'http://www.ugm.cl/carreras/animacion-digital-3d/',
  1611: 'http://www.ugm.cl/carreras/ingenieria-administracion-empresas-regular/',
  1612: 'http://www.ugm.cl/carreras/derecho/',
  1613: 'http://www.ugm.cl/carreras/diseno-crossmedia/',
  1614: 'http://www.ugm.cl/carreras/ingenieria-civil-industrial/',
  1615: 'http://www.ugm.cl/carreras/ingenieria-civil-industrial/',
  1616: 'http://www.ugm.cl/carreras/ingenieria-comercial/',
  1617: 'http://www.ugm.cl/carreras/ingenieria-comercial/',
  1618: 'http://www.ugm.cl/carreras/ingenieria-administracion-empresas-regular/',
  1619: 'http://www.ugm.cl/facultades/facultad-de-educacion/',
  1620: 'http://www.ugm.cl/carreras/psicologia/',

};

export default (state = initialState, action) => state;
