const initialState = {
  1512: 'http://admisionucentral.cl/administracion-publica/',
  1513: 'http://admisionucentral.cl/arquitectura/',
  1514: 'http://admisionucentral.cl/arquitectura-del-paisaje/',
  1515: 'http://admisionucentral.cl/ciencia-politica/',
  1516: 'http://admisionucentral.cl/contador-auditor/',
  1517: 'http://admisionucentral.cl/derecho-la-serena/',
  1518: 'http://admisionucentral.cl/derecho',
  1519: 'http://admisionucentral.cl/educacion-parvularia/',
  1520: 'http://admisionucentral.cl/enfermeria/',
  1521: 'http://admisionucentral.cl/geologia/',
  1522: 'http://admisionucentral.cl/computacion-informatica/',
  1523: 'http://admisionucentral.cl/minas/',
  1524: 'http://admisionucentral.cl/obras-civiles/',
  1525: 'http://admisionucentral.cl/industrial/',
  1526: 'http://admisionucentral.cl/ingenieria-comercial-la-serena/',
  1527: 'http://admisionucentral.cl/ingenieria-comercial/',
  1528: 'http://admisionucentral.cl/administracion-de-negocios/',
  1529: 'http://admisionucentral.cl/agronegocios/',
  1530: 'http://admisionucentral.cl/construccion/',
  1531: 'http://admisionucentral.cl/control-gestion/',
  1532: 'http://admisionucentral.cl/nutricion-dietetica/',
  1533: 'http://admisionucentral.cl/educacion-diferencial/',
  1534: 'http://admisionucentral.cl/educacion-diferencial-la-serena/',
  1535: 'http://admisionucentral.cl/educacion-fisica/',
  1536: 'http://admisionucentral.cl/educacion-fisica-la-serena/',
  1537: 'http://admisionucentral.cl/educacion-general-basica/',
  1538: 'http://admisionucentral.cl/lengua-cultura-inglesa/',
  1539: 'http://admisionucentral.cl/matematicas-estadisticas/',
  1540: 'http://admisionucentral.cl/periodismo/',
  1541: 'http://admisionucentral.cl/psicologia/',
  1542: 'http://admisionucentral.cl/psicologia-la-serena/',
  1543: 'http://admisionucentral.cl/publicidad/',
  1544: 'http://admisionucentral.cl/sociologia-la-serena/',
  1545: 'http://admisionucentral.cl/sociologia/',
  1546: 'http://admisionucentral.cl/tecnologia-medica/',
  1547: 'http://admisionucentral.cl/terapia-ocupacional/',
  1548: 'http://admisionucentral.cl/trabajo-social/',
  1610: 'http://www.ugm.cl/carreras/animacion-digital-3d/',
  1611: 'http://www.ugm.cl/carreras/ingenieria-administracion-empresas-regular/',
  1612: 'http://www.ugm.cl/carreras/derecho/',
  1613: 'http://www.ugm.cl/carreras/diseno-crossmedia/',
  1614: 'http://www.ugm.cl/carreras/ingenieria-civil-industrial/',
  1615: 'http://www.ugm.cl/carreras/ingenieria-civil-industrial/',
  1616: 'http://www.ugm.cl/carreras/ingenieria-comercial/',
  1617: 'http://www.ugm.cl/carreras/ingenieria-comercial/',
  1618: 'http://www.ugm.cl/carreras/ingenieria-administracion-empresas-regular/',
  1619: 'http://www.ugm.cl/facultades/facultad-de-educacion/',
  1620: 'http://www.ugm.cl/carreras/psicologia/',

};

export default (state = initialState, action) => state;
